export const SEO_KEYWORDS = {
    core: [
        "french bulldog puppies",
        "french bulldog puppy for sale",
        "frenchie puppies for sale",
        "french bulldog breeder",
        "french bulldog stud service",
        "frenchie stud",
        "french bulldog male for stud",
        "french bulldog female puppy",
        "akc french bulldog",
        "exotic french bulldog",
        "micro french bulldog",
        "mini french bulldog",
        "teacup french bulldog",
        "french bulldog bloodline",
        "champion bloodline french bulldog",
    ],
    colors: {
        blue: [
            "blue french bulldog",
            "blue fawn french bulldog",
            "solid blue french bulldog",
            "blue brindle french bulldog",
        ],
        chocolate: [
            "chocolate french bulldog",
            "choco french bulldog",
            "choco tan french bulldog",
            "chocolate merle french bulldog",
        ],
        lilac: [
            "lilac french bulldog",
            "lilac tan french bulldog",
            "lilac fawn french bulldog",
        ],
        isabella: [
            "isabella french bulldog",
            "isabella tan french bulldog",
        ],
        cream: [
            "cream french bulldog",
            "platinum french bulldog",
            "ivory french bulldog",
        ],
        black: [
            "black french bulldog",
            "black masked french bulldog",
        ],
        merle: [
            "merle french bulldog",
            "blue merle french bulldog",
            "chocolate merle french bulldog",
        ],
    },
    exotic: [
        "pink french bulldog",
        "pink choco french bulldog",
        "pink chocolate frenchie",
        "pink lilac french bulldog",
        "fluffy french bulldog",
        "long hair french bulldog",
        "hairy french bulldog",
        "fluffy carrier frenchie",
        "new shade french bulldog",
        "rare color french bulldog",
        "exotic color french bulldog",
        "high color french bulldog",
        "dna tested french bulldog",
        "health tested french bulldog",
        "color tested french bulldog",
    ],
    slang: [
        "top quality french bulldog",
        "best french bulldog breeder",
        "small batch french bulldog breeder",
        "private french bulldog breeder",
        "exclusive french bulldog puppies",
        "french bulldog kennel",
        "french bulldog bloodline breeder",
        "french bulldog program",
        "stud contract french bulldog",
        "proven stud french bulldog",
        "stud fee french bulldog",
    ],
    transactional: [
        "buy french bulldog puppy",
        "french bulldog puppies near me",
        "french bulldog for sale usa",
        "french bulldog breeder near me",
        "cheap french bulldog puppies",
        "affordable french bulldog puppies",
        "payment plan french bulldog",
        "french bulldog shipping usa",
        "nationwide french bulldog delivery",
    ],
    geo_patterns: [
        "french bulldog breeder in [city]",
        "french bulldog puppies in [city]",
        "french bulldog puppies near [city]",
        "french bulldog stud service in [city]",
        "blue french bulldog breeder in [city]",
        "exotic french bulldog breeder in [city]",
        "fluffy french bulldog breeder in [city]",
        "french bulldog puppies [state]",
        "french bulldog breeder [state]",
    ],
    advanced_breeding: [
        "french bulldog color genetics",
        "french bulldog dna color testing",
        "french bulldog breeding rights",
        "french bulldog stud contract",
        "french bulldog reproduction",
        "progesterone testing french bulldog",
        "artificial insemination french bulldog",
        "french bulldog breeding program",
    ],
    trendy: [
        "instagram french bulldog breeder",
        "tiktok french bulldog puppies",
        "viral french bulldog",
        "celebrity french bulldog breeder",
        "luxury french bulldog",
    ],
    variations: [
        "micro exotic french bulldog",
        "big rope french bulldog",
        "short back french bulldog",
        "thick bone french bulldog",
        "wide chest french bulldog",
        "compact french bulldog",
        "short muzzle french bulldog",
        "extreme head french bulldog",
    ],
    hidden: [
        "french bulldog without papers",
        "french bulldog non akc",
        "french bulldog off standard colors",
        "rare french bulldog colors",
        "illegal french bulldog colors",
    ],
}
